
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpcie.h"

/*
* The configuration table for devices
*/

XPcie_Config XPcie_ConfigTable[] =
{
	{
		XPAR_PCIE_BRIDGE_DEVICE_ID,
		XPAR_PCIE_BRIDGE_BASEADDR,
		XPAR_PCIE_BRIDGE_IPIFBAR_NUM,
		XPAR_PCIE_BRIDGE_INCLUDE_BAROFFSET_REG,
		XPAR_PCIE_BRIDGE_INCLUDE_RC,
		XPAR_PCIE_BRIDGE_ECAM_BASEADDR,
		XPAR_PCIE_BRIDGE_ECAM_HIGHADDR
	}
};


