
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdsdac.h"

/*
* The configuration table for devices
*/

XDsDac_Config XDsDac_ConfigTable[] =
{
	{
		XPAR_CTRL_STICK_L_X_DEVICE_ID,
		XPAR_CTRL_STICK_L_X_BASEADDR
	},
	{
		XPAR_CTRL_STICK_L_Y_DEVICE_ID,
		XPAR_CTRL_STICK_L_Y_BASEADDR
	},
	{
		XPAR_CTRL_STICK_R_X_DEVICE_ID,
		XPAR_CTRL_STICK_R_X_BASEADDR
	},
	{
		XPAR_CTRL_STICK_R_Y_DEVICE_ID,
		XPAR_CTRL_STICK_R_Y_BASEADDR
	},
	{
		XPAR_CTRL_TRIGGER_LT_DEVICE_ID,
		XPAR_CTRL_TRIGGER_LT_BASEADDR
	},
	{
		XPAR_CTRL_TRIGGER_RT_DEVICE_ID,
		XPAR_CTRL_TRIGGER_RT_BASEADDR
	}
};


